---
abstract: 'FAST Analysis of Sequences Toolbox'
author:
  - 'David H. Ardell <dhard@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FAST
no_index:
  directory:
    - t
    - inc
requires:
  Bit::Vector: 0
  Pod::Usage: 0
  Sort::Key: 0
  Sort::MergeSort: 0
  perl: 0
version: 1.06
